apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dynamic2-backend
      name: dynamic2-backend
      namespace: scrape
    spec:
      ports:
        - name: "8000"
          port: 8000
          targetPort: 8000
      selector:
        io.kompose.service: dynamic2-backend
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dynamic2-frontend
      name: dynamic2-frontend
      namespace: scrape
    spec:
      ports:
        - name: "8083"
          port: 8083
          targetPort: 80
      selector:
        io.kompose.service: dynamic2-frontend
    status:
      loadBalancer: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dynamic2-backend
      name: dynamic2-backend
      namespace: scrape
    spec:
      replicas: 1
      revisionHistoryLimit: 1
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
            kompose.version: 1.20.0 ()
          creationTimestamp: null
          labels:
            io.kompose.service: dynamic2-backend
        spec:
          containers:
            - env:
                - name: APP_ENV
                  value: production
                - name: PGSQL_DATABASE
                  value: scrape_maoyan
                - name: PGSQL_HOST
                  valueFrom:
                    secretKeyRef:
                      name: pgsql
                      key: PGSQL_HOST
                - name: PGSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pgsql
                      key: PGSQL_PASSWORD
                - name: PGSQL_PORT
                  valueFrom:
                    secretKeyRef:
                      name: pgsql
                      key: PGSQL_PORT
                - name: PGSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: pgsql
                      key: PGSQL_USER
              image: germey/scrape-dynamic2-backend:${TAG}
              name: scrape-dynamic2-backend
              ports:
                - containerPort: 8000
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: dynamic2-frontend
      name: dynamic2-frontend
      namespace: scrape
    spec:
      replicas: 1
      revisionHistoryLimit: 1
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
            kompose.version: 1.20.0 ()
          creationTimestamp: null
          labels:
            io.kompose.service: dynamic2-frontend
        spec:
          containers:
            - image: germey/scrape-dynamic2-frontend:${TAG}
              name: scrape-dynamic2-frontend
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-dynamic2
  namespace: scrape
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - dynamic2.scrape.cuiqingcai.com
      secretName: tls-scrape-cuiqingcai-com
  rules:
    - host: dynamic2.scrape.cuiqingcai.com
      http:
        paths:
          - backend:
              serviceName: dynamic2-frontend
              servicePort: 80
            path: /